base:
    # Set the directory path where the node will store its database
    data_dir: "/opt/aptos/data"
    role: "full_node"
    waypoint:
        # Set this to the waypoint value provided by the blockchain network.
        # Ensure this matches the corresponding genesis file location below.
        from_file: "./waypoint.txt"

execution:
    # Path to the genesis.blob file (full paths are recommended)
    # This must correspond to the waypoint above. If updating the waypoint
    # without a matching genesis file, leave this path empty.
    genesis_file_location: "./genesis.blob"
    # Path to the genesis waypoint file
    genesis_waypoint:
        from_file: "/opt/aptos/genesis/genesis_waypoint.txt"

storage:
  rocksdb_configs:
    enable_storage_sharding: false

full_node_networks:
  - network_id: "public"
    discovery_method: "none"
    # Optional: Enable this if you want other PFNs to connect to your node
    listen_address: "/ip4/0.0.0.0/tcp/6182"
    # Configure upstream PFN connections here
    seeds:
      9967EBF40AC8C2CCB38709488952DA1826176584EA3067B63B1695362ECB3D1F:
        addresses:
        - "/dns/testnet.movementnetwork.xyz/tcp/6182/noise-ik/9967EBF40AC8C2CCB38709488952DA1826176584EA3067B63B1695362ECB3D1F/handshake/0"
        role: "Upstream"
api:
    enabled: true
    address: 127.0.0.1:8080

state_sync:
  state_sync_driver:
    bootstrapping_mode: DownloadLatestStates
    continuous_syncing_mode: ApplyTransactionOutputs
