name: "🔨 Build Version"
run-name: "Building version for ${{ github.ref_name }}"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to build (branch, tag, sha).'
        required: true
        default: 'main'
      profile:
        description: 'The cargo build profile to use.'
        required: true
        default: 'dev'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.chop_sha.outputs.short_sha }}
      build_date: ${{ steps.build_date.outputs.build_date }}
      git_branch: ${{ steps.git_branch.outputs.git_branch }}
      git_tag: ${{ steps.git_tag.outputs.git_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha}}
      - id: chop_sha
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
      - id: build_date
        run: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
      - id: git_branch
        run: |
          if [ "${GITHUB_REF_TYPE}" = "branch" ]; then
            echo "git_branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "git_branch=detached" >> $GITHUB_OUTPUT
          fi
      - id: git_tag
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "git_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "git_tag=none" >> $GITHUB_OUTPUT
          fi
  build-binaries:
    runs-on: k8s-movement-labs
    name: "Build ${{ matrix.binary.package }} with Nix"
    strategy:
      matrix:
        binary:
          - package: "aptos-node"
          - package: "aptos"
          - package: "l1-migration"
    env:
      TARGET_FOLDER: target/debug
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha}}
      - name: Build binary ${{ matrix.binary.package }}
        uses: ./.github/actions/build-binary
        with:
          binary_package: ${{ matrix.binary.package }}
          profile: ${{ inputs.profile || 'dev' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build-docker:
    needs: 
      - setup
      - build-binaries
    runs-on: ubuntu-latest
    name: "Build Docker Images"
    permissions:
      contents: read
      packages: write
    env:
      TARGET_FOLDER: target/debug
      SHORT_SHA: ${{ needs.setup.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha}}
      # Download artifacts
      - name: Download aptos-node binary
        uses: actions/download-artifact@v4
        with:
          name: aptos-node-${{ env.SHORT_SHA }}
          path: ${{ env.TARGET_FOLDER }}
      - name: Download aptos binary
        uses: actions/download-artifact@v4
        with:
          name: aptos-${{ env.SHORT_SHA }}
          path: ${{ env.TARGET_FOLDER }}
      - name: Download l1-migration binary
        uses: actions/download-artifact@v4
        with:
          name: l1-migration-${{ env.SHORT_SHA }}
          path: ${{ env.TARGET_FOLDER }}
      - name: List binaries
        run: ls -la ${{ env.TARGET_FOLDER }}
        
      - name: Build Container
        uses: ./.github/actions/build-container
        with:
          image_name: ghcr.io/movementlabsxyz/aptos-node
          dockerfile_subdir: aptos-node
          binaries_to_download: aptos-node,aptos,l1-migration
          build_args: BINARY_PATH=${{ env.TARGET_FOLDER }},GIT_SHA=${{ github.sha }},GIT_TAG=${{ needs.setup.outputs.git_tag }},GIT_BRANCH=${{ needs.setup.outputs.git_branch }},BUILD_DATE=${{ needs.setup.outputs.build_date }}
          ghcr_username: ${{ vars.INFRA_GH_USER }}
          ghcr_password: ${{ secrets.INFRA_GH_PAT }}