name: Build Docker Images

on:
  push:
    branches: [ main, ci/* ]
  workflow_dispatch:
    inputs:
      GIT_SHA:
        description: 'Git SHA to build'
        required: false
      FEATURES:
        description: 'Cargo features to enable'
        required: false
      PROFILE:
        description: 'Cargo build profile'
        required: false
        default: 'release'

# Add permissions block to ensure the workflow has access to packages
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history
          ref: ${{ github.ref }}  # Use the full ref to ensure we're on the right branch
          token: ${{ secrets.GH_PAT }}  # Use PAT for checkout
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}  # Use the PAT owner's username
          password: ${{ secrets.GH_PAT }}  # Use PAT instead of GITHUB_TOKEN
      
      - name: Build and Push Images
        run: |
          export TARGET_CACHE_ID=${GITHUB_REF#refs/heads/}
          export GHCR_ORG="movementlabsxyz"
          export PROFILE=${PROFILE:-release}
          export FEATURES=${FEATURES:-""}
          export CARGO_TARGET_DIR="target/${FEATURES:-default}"
          
          docker/builder/docker-bake-rust-all.sh 